/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserDataAttributes{}

// UserDataAttributes struct for UserDataAttributes
type UserDataAttributes struct {
	// Username
	Username string `json:"username"`
	// User role
	Role string `json:"role"`
	// User avatar
	Avatar string `json:"avatar"`
	// User updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// User created at
	CreatedAt time.Time `json:"created_at"`
	// User organization
	Organizations []string `json:"organizations,omitempty"`
	// User projects
	Projects []string `json:"projects,omitempty"`
	// User ideas
	Ideas []string `json:"ideas,omitempty"`
	// User reports sent
	ReportsSent []string `json:"reports_sent,omitempty"`
	// User reports received
	ReportsReceived []string `json:"reports_received,omitempty"`
	Ban *UserDataAttributesBan `json:"ban,omitempty"`
}

type _UserDataAttributes UserDataAttributes

// NewUserDataAttributes instantiates a new UserDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserDataAttributes(username string, role string, avatar string, createdAt time.Time) *UserDataAttributes {
	this := UserDataAttributes{}
	this.Username = username
	this.Role = role
	this.Avatar = avatar
	this.CreatedAt = createdAt
	return &this
}

// NewUserDataAttributesWithDefaults instantiates a new UserDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserDataAttributesWithDefaults() *UserDataAttributes {
	this := UserDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *UserDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetRole returns the Role field value
func (o *UserDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UserDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetAvatar returns the Avatar field value
func (o *UserDataAttributes) GetAvatar() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetAvatarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Avatar, true
}

// SetAvatar sets field value
func (o *UserDataAttributes) SetAvatar(v string) {
	o.Avatar = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *UserDataAttributes) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UserDataAttributes) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *UserDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *UserDataAttributes) GetOrganizations() []string {
	if o == nil || IsNil(o.Organizations) {
		var ret []string
		return ret
	}
	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetOrganizationsOk() ([]string, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *UserDataAttributes) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given []string and assigns it to the Organizations field.
func (o *UserDataAttributes) SetOrganizations(v []string) {
	o.Organizations = v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *UserDataAttributes) GetProjects() []string {
	if o == nil || IsNil(o.Projects) {
		var ret []string
		return ret
	}
	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetProjectsOk() ([]string, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *UserDataAttributes) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given []string and assigns it to the Projects field.
func (o *UserDataAttributes) SetProjects(v []string) {
	o.Projects = v
}

// GetIdeas returns the Ideas field value if set, zero value otherwise.
func (o *UserDataAttributes) GetIdeas() []string {
	if o == nil || IsNil(o.Ideas) {
		var ret []string
		return ret
	}
	return o.Ideas
}

// GetIdeasOk returns a tuple with the Ideas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetIdeasOk() ([]string, bool) {
	if o == nil || IsNil(o.Ideas) {
		return nil, false
	}
	return o.Ideas, true
}

// HasIdeas returns a boolean if a field has been set.
func (o *UserDataAttributes) HasIdeas() bool {
	if o != nil && !IsNil(o.Ideas) {
		return true
	}

	return false
}

// SetIdeas gets a reference to the given []string and assigns it to the Ideas field.
func (o *UserDataAttributes) SetIdeas(v []string) {
	o.Ideas = v
}

// GetReportsSent returns the ReportsSent field value if set, zero value otherwise.
func (o *UserDataAttributes) GetReportsSent() []string {
	if o == nil || IsNil(o.ReportsSent) {
		var ret []string
		return ret
	}
	return o.ReportsSent
}

// GetReportsSentOk returns a tuple with the ReportsSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetReportsSentOk() ([]string, bool) {
	if o == nil || IsNil(o.ReportsSent) {
		return nil, false
	}
	return o.ReportsSent, true
}

// HasReportsSent returns a boolean if a field has been set.
func (o *UserDataAttributes) HasReportsSent() bool {
	if o != nil && !IsNil(o.ReportsSent) {
		return true
	}

	return false
}

// SetReportsSent gets a reference to the given []string and assigns it to the ReportsSent field.
func (o *UserDataAttributes) SetReportsSent(v []string) {
	o.ReportsSent = v
}

// GetReportsReceived returns the ReportsReceived field value if set, zero value otherwise.
func (o *UserDataAttributes) GetReportsReceived() []string {
	if o == nil || IsNil(o.ReportsReceived) {
		var ret []string
		return ret
	}
	return o.ReportsReceived
}

// GetReportsReceivedOk returns a tuple with the ReportsReceived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetReportsReceivedOk() ([]string, bool) {
	if o == nil || IsNil(o.ReportsReceived) {
		return nil, false
	}
	return o.ReportsReceived, true
}

// HasReportsReceived returns a boolean if a field has been set.
func (o *UserDataAttributes) HasReportsReceived() bool {
	if o != nil && !IsNil(o.ReportsReceived) {
		return true
	}

	return false
}

// SetReportsReceived gets a reference to the given []string and assigns it to the ReportsReceived field.
func (o *UserDataAttributes) SetReportsReceived(v []string) {
	o.ReportsReceived = v
}

// GetBan returns the Ban field value if set, zero value otherwise.
func (o *UserDataAttributes) GetBan() UserDataAttributesBan {
	if o == nil || IsNil(o.Ban) {
		var ret UserDataAttributesBan
		return ret
	}
	return *o.Ban
}

// GetBanOk returns a tuple with the Ban field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserDataAttributes) GetBanOk() (*UserDataAttributesBan, bool) {
	if o == nil || IsNil(o.Ban) {
		return nil, false
	}
	return o.Ban, true
}

// HasBan returns a boolean if a field has been set.
func (o *UserDataAttributes) HasBan() bool {
	if o != nil && !IsNil(o.Ban) {
		return true
	}

	return false
}

// SetBan gets a reference to the given UserDataAttributesBan and assigns it to the Ban field.
func (o *UserDataAttributes) SetBan(v UserDataAttributesBan) {
	o.Ban = &v
}

func (o UserDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["role"] = o.Role
	toSerialize["avatar"] = o.Avatar
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	if !IsNil(o.Ideas) {
		toSerialize["ideas"] = o.Ideas
	}
	if !IsNil(o.ReportsSent) {
		toSerialize["reports_sent"] = o.ReportsSent
	}
	if !IsNil(o.ReportsReceived) {
		toSerialize["reports_received"] = o.ReportsReceived
	}
	if !IsNil(o.Ban) {
		toSerialize["ban"] = o.Ban
	}
	return toSerialize, nil
}

func (o *UserDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"role",
		"avatar",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserDataAttributes := _UserDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserDataAttributes)

	if err != nil {
		return err
	}

	*o = UserDataAttributes(varUserDataAttributes)

	return err
}

type NullableUserDataAttributes struct {
	value *UserDataAttributes
	isSet bool
}

func (v NullableUserDataAttributes) Get() *UserDataAttributes {
	return v.value
}

func (v *NullableUserDataAttributes) Set(val *UserDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserDataAttributes(val *UserDataAttributes) *NullableUserDataAttributes {
	return &NullableUserDataAttributes{value: val, isSet: true}
}

func (v NullableUserDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


