/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCreateDataAttributes{}

// UserCreateDataAttributes struct for UserCreateDataAttributes
type UserCreateDataAttributes struct {
	// Username
	Username string `json:"username"`
	// User title
	Title *string `json:"title,omitempty"`
	// User status
	Status *string `json:"status,omitempty"`
	// User avatar
	Avatar *string `json:"avatar,omitempty"`
	// User bio
	Bio *string `json:"bio,omitempty"`
}

type _UserCreateDataAttributes UserCreateDataAttributes

// NewUserCreateDataAttributes instantiates a new UserCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateDataAttributes(username string) *UserCreateDataAttributes {
	this := UserCreateDataAttributes{}
	this.Username = username
	return &this
}

// NewUserCreateDataAttributesWithDefaults instantiates a new UserCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateDataAttributesWithDefaults() *UserCreateDataAttributes {
	this := UserCreateDataAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *UserCreateDataAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserCreateDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserCreateDataAttributes) SetUsername(v string) {
	o.Username = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UserCreateDataAttributes) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateDataAttributes) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UserCreateDataAttributes) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UserCreateDataAttributes) SetTitle(v string) {
	o.Title = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UserCreateDataAttributes) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UserCreateDataAttributes) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *UserCreateDataAttributes) SetStatus(v string) {
	o.Status = &v
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *UserCreateDataAttributes) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateDataAttributes) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *UserCreateDataAttributes) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *UserCreateDataAttributes) SetAvatar(v string) {
	o.Avatar = &v
}

// GetBio returns the Bio field value if set, zero value otherwise.
func (o *UserCreateDataAttributes) GetBio() string {
	if o == nil || IsNil(o.Bio) {
		var ret string
		return ret
	}
	return *o.Bio
}

// GetBioOk returns a tuple with the Bio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateDataAttributes) GetBioOk() (*string, bool) {
	if o == nil || IsNil(o.Bio) {
		return nil, false
	}
	return o.Bio, true
}

// HasBio returns a boolean if a field has been set.
func (o *UserCreateDataAttributes) HasBio() bool {
	if o != nil && !IsNil(o.Bio) {
		return true
	}

	return false
}

// SetBio gets a reference to the given string and assigns it to the Bio field.
func (o *UserCreateDataAttributes) SetBio(v string) {
	o.Bio = &v
}

func (o UserCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	if !IsNil(o.Bio) {
		toSerialize["bio"] = o.Bio
	}
	return toSerialize, nil
}

func (o *UserCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserCreateDataAttributes := _UserCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = UserCreateDataAttributes(varUserCreateDataAttributes)

	return err
}

type NullableUserCreateDataAttributes struct {
	value *UserCreateDataAttributes
	isSet bool
}

func (v NullableUserCreateDataAttributes) Get() *UserCreateDataAttributes {
	return v.value
}

func (v *NullableUserCreateDataAttributes) Set(val *UserCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateDataAttributes(val *UserCreateDataAttributes) *NullableUserCreateDataAttributes {
	return &NullableUserCreateDataAttributes{value: val, isSet: true}
}

func (v NullableUserCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


