/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberDataRelationshipsUserData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberDataRelationshipsUserData{}

// MemberDataRelationshipsUserData struct for MemberDataRelationshipsUserData
type MemberDataRelationshipsUserData struct {
	// User ID
	Id string `json:"id"`
	Type string `json:"type"`
}

type _MemberDataRelationshipsUserData MemberDataRelationshipsUserData

// NewMemberDataRelationshipsUserData instantiates a new MemberDataRelationshipsUserData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberDataRelationshipsUserData(id string, type_ string) *MemberDataRelationshipsUserData {
	this := MemberDataRelationshipsUserData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewMemberDataRelationshipsUserDataWithDefaults instantiates a new MemberDataRelationshipsUserData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberDataRelationshipsUserDataWithDefaults() *MemberDataRelationshipsUserData {
	this := MemberDataRelationshipsUserData{}
	return &this
}

// GetId returns the Id field value
func (o *MemberDataRelationshipsUserData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsUserData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemberDataRelationshipsUserData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *MemberDataRelationshipsUserData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsUserData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MemberDataRelationshipsUserData) SetType(v string) {
	o.Type = v
}

func (o MemberDataRelationshipsUserData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberDataRelationshipsUserData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *MemberDataRelationshipsUserData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberDataRelationshipsUserData := _MemberDataRelationshipsUserData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberDataRelationshipsUserData)

	if err != nil {
		return err
	}

	*o = MemberDataRelationshipsUserData(varMemberDataRelationshipsUserData)

	return err
}

type NullableMemberDataRelationshipsUserData struct {
	value *MemberDataRelationshipsUserData
	isSet bool
}

func (v NullableMemberDataRelationshipsUserData) Get() *MemberDataRelationshipsUserData {
	return v.value
}

func (v *NullableMemberDataRelationshipsUserData) Set(val *MemberDataRelationshipsUserData) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberDataRelationshipsUserData) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberDataRelationshipsUserData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberDataRelationshipsUserData(val *MemberDataRelationshipsUserData) *NullableMemberDataRelationshipsUserData {
	return &NullableMemberDataRelationshipsUserData{value: val, isSet: true}
}

func (v NullableMemberDataRelationshipsUserData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberDataRelationshipsUserData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


