/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberDataRelationshipsTeamsDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberDataRelationshipsTeamsDataInner{}

// MemberDataRelationshipsTeamsDataInner struct for MemberDataRelationshipsTeamsDataInner
type MemberDataRelationshipsTeamsDataInner struct {
	// Team ID
	Id string `json:"id"`
	Type string `json:"type"`
}

type _MemberDataRelationshipsTeamsDataInner MemberDataRelationshipsTeamsDataInner

// NewMemberDataRelationshipsTeamsDataInner instantiates a new MemberDataRelationshipsTeamsDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberDataRelationshipsTeamsDataInner(id string, type_ string) *MemberDataRelationshipsTeamsDataInner {
	this := MemberDataRelationshipsTeamsDataInner{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewMemberDataRelationshipsTeamsDataInnerWithDefaults instantiates a new MemberDataRelationshipsTeamsDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberDataRelationshipsTeamsDataInnerWithDefaults() *MemberDataRelationshipsTeamsDataInner {
	this := MemberDataRelationshipsTeamsDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *MemberDataRelationshipsTeamsDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsTeamsDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemberDataRelationshipsTeamsDataInner) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *MemberDataRelationshipsTeamsDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MemberDataRelationshipsTeamsDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MemberDataRelationshipsTeamsDataInner) SetType(v string) {
	o.Type = v
}

func (o MemberDataRelationshipsTeamsDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberDataRelationshipsTeamsDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *MemberDataRelationshipsTeamsDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberDataRelationshipsTeamsDataInner := _MemberDataRelationshipsTeamsDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberDataRelationshipsTeamsDataInner)

	if err != nil {
		return err
	}

	*o = MemberDataRelationshipsTeamsDataInner(varMemberDataRelationshipsTeamsDataInner)

	return err
}

type NullableMemberDataRelationshipsTeamsDataInner struct {
	value *MemberDataRelationshipsTeamsDataInner
	isSet bool
}

func (v NullableMemberDataRelationshipsTeamsDataInner) Get() *MemberDataRelationshipsTeamsDataInner {
	return v.value
}

func (v *NullableMemberDataRelationshipsTeamsDataInner) Set(val *MemberDataRelationshipsTeamsDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberDataRelationshipsTeamsDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberDataRelationshipsTeamsDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberDataRelationshipsTeamsDataInner(val *MemberDataRelationshipsTeamsDataInner) *NullableMemberDataRelationshipsTeamsDataInner {
	return &NullableMemberDataRelationshipsTeamsDataInner{value: val, isSet: true}
}

func (v NullableMemberDataRelationshipsTeamsDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberDataRelationshipsTeamsDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


