/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersCollection{}

// UsersCollection struct for UsersCollection
type UsersCollection struct {
	Data []UserData `json:"data"`
	Links LinksPagination `json:"links"`
}

type _UsersCollection UsersCollection

// NewUsersCollection instantiates a new UsersCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersCollection(data []UserData, links LinksPagination) *UsersCollection {
	this := UsersCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewUsersCollectionWithDefaults instantiates a new UsersCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersCollectionWithDefaults() *UsersCollection {
	this := UsersCollection{}
	return &this
}

// GetData returns the Data field value
func (o *UsersCollection) GetData() []UserData {
	if o == nil {
		var ret []UserData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UsersCollection) GetDataOk() ([]UserData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *UsersCollection) SetData(v []UserData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *UsersCollection) GetLinks() LinksPagination {
	if o == nil {
		var ret LinksPagination
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *UsersCollection) GetLinksOk() (*LinksPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *UsersCollection) SetLinks(v LinksPagination) {
	o.Links = v
}

func (o UsersCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *UsersCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersCollection := _UsersCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersCollection)

	if err != nil {
		return err
	}

	*o = UsersCollection(varUsersCollection)

	return err
}

type NullableUsersCollection struct {
	value *UsersCollection
	isSet bool
}

func (v NullableUsersCollection) Get() *UsersCollection {
	return v.value
}

func (v *NullableUsersCollection) Set(val *UsersCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersCollection(val *UsersCollection) *NullableUsersCollection {
	return &NullableUsersCollection{value: val, isSet: true}
}

func (v NullableUsersCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


