/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the TeamDataRelationshipsMembers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamDataRelationshipsMembers{}

// TeamDataRelationshipsMembers struct for TeamDataRelationshipsMembers
type TeamDataRelationshipsMembers struct {
	Data []TeamDataRelationshipsMembersDataInner `json:"data,omitempty"`
}

// NewTeamDataRelationshipsMembers instantiates a new TeamDataRelationshipsMembers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamDataRelationshipsMembers() *TeamDataRelationshipsMembers {
	this := TeamDataRelationshipsMembers{}
	return &this
}

// NewTeamDataRelationshipsMembersWithDefaults instantiates a new TeamDataRelationshipsMembers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamDataRelationshipsMembersWithDefaults() *TeamDataRelationshipsMembers {
	this := TeamDataRelationshipsMembers{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TeamDataRelationshipsMembers) GetData() []TeamDataRelationshipsMembersDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []TeamDataRelationshipsMembersDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TeamDataRelationshipsMembers) GetDataOk() ([]TeamDataRelationshipsMembersDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TeamDataRelationshipsMembers) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []TeamDataRelationshipsMembersDataInner and assigns it to the Data field.
func (o *TeamDataRelationshipsMembers) SetData(v []TeamDataRelationshipsMembersDataInner) {
	o.Data = v
}

func (o TeamDataRelationshipsMembers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamDataRelationshipsMembers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTeamDataRelationshipsMembers struct {
	value *TeamDataRelationshipsMembers
	isSet bool
}

func (v NullableTeamDataRelationshipsMembers) Get() *TeamDataRelationshipsMembers {
	return v.value
}

func (v *NullableTeamDataRelationshipsMembers) Set(val *TeamDataRelationshipsMembers) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamDataRelationshipsMembers) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamDataRelationshipsMembers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamDataRelationshipsMembers(val *TeamDataRelationshipsMembers) *NullableTeamDataRelationshipsMembers {
	return &NullableTeamDataRelationshipsMembers{value: val, isSet: true}
}

func (v NullableTeamDataRelationshipsMembers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamDataRelationshipsMembers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


