/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserCollectionDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCollectionDataAttributes{}

// UserCollectionDataAttributes struct for UserCollectionDataAttributes
type UserCollectionDataAttributes struct {
	Users []UserDataAttributes `json:"users"`
}

type _UserCollectionDataAttributes UserCollectionDataAttributes

// NewUserCollectionDataAttributes instantiates a new UserCollectionDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCollectionDataAttributes(users []UserDataAttributes) *UserCollectionDataAttributes {
	this := UserCollectionDataAttributes{}
	this.Users = users
	return &this
}

// NewUserCollectionDataAttributesWithDefaults instantiates a new UserCollectionDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCollectionDataAttributesWithDefaults() *UserCollectionDataAttributes {
	this := UserCollectionDataAttributes{}
	return &this
}

// GetUsers returns the Users field value
func (o *UserCollectionDataAttributes) GetUsers() []UserDataAttributes {
	if o == nil {
		var ret []UserDataAttributes
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *UserCollectionDataAttributes) GetUsersOk() ([]UserDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *UserCollectionDataAttributes) SetUsers(v []UserDataAttributes) {
	o.Users = v
}

func (o UserCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCollectionDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	return toSerialize, nil
}

func (o *UserCollectionDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserCollectionDataAttributes := _UserCollectionDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserCollectionDataAttributes)

	if err != nil {
		return err
	}

	*o = UserCollectionDataAttributes(varUserCollectionDataAttributes)

	return err
}

type NullableUserCollectionDataAttributes struct {
	value *UserCollectionDataAttributes
	isSet bool
}

func (v NullableUserCollectionDataAttributes) Get() *UserCollectionDataAttributes {
	return v.value
}

func (v *NullableUserCollectionDataAttributes) Set(val *UserCollectionDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCollectionDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCollectionDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCollectionDataAttributes(val *UserCollectionDataAttributes) *NullableUserCollectionDataAttributes {
	return &NullableUserCollectionDataAttributes{value: val, isSet: true}
}

func (v NullableUserCollectionDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCollectionDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


