/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the TeamDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamDataAttributes{}

// TeamDataAttributes struct for TeamDataAttributes
type TeamDataAttributes struct {
	// Team name
	Name string `json:"name"`
	// Team description
	Description string `json:"description"`
	Members []MemberDataAttributes `json:"members"`
	// Team created at
	CreatedAt time.Time `json:"created_at"`
}

type _TeamDataAttributes TeamDataAttributes

// NewTeamDataAttributes instantiates a new TeamDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamDataAttributes(name string, description string, members []MemberDataAttributes, createdAt time.Time) *TeamDataAttributes {
	this := TeamDataAttributes{}
	this.Name = name
	this.Description = description
	this.Members = members
	this.CreatedAt = createdAt
	return &this
}

// NewTeamDataAttributesWithDefaults instantiates a new TeamDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamDataAttributesWithDefaults() *TeamDataAttributes {
	this := TeamDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *TeamDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TeamDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TeamDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *TeamDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TeamDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TeamDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetMembers returns the Members field value
func (o *TeamDataAttributes) GetMembers() []MemberDataAttributes {
	if o == nil {
		var ret []MemberDataAttributes
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *TeamDataAttributes) GetMembersOk() ([]MemberDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *TeamDataAttributes) SetMembers(v []MemberDataAttributes) {
	o.Members = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TeamDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TeamDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TeamDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o TeamDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["members"] = o.Members
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *TeamDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"members",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamDataAttributes := _TeamDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamDataAttributes)

	if err != nil {
		return err
	}

	*o = TeamDataAttributes(varTeamDataAttributes)

	return err
}

type NullableTeamDataAttributes struct {
	value *TeamDataAttributes
	isSet bool
}

func (v NullableTeamDataAttributes) Get() *TeamDataAttributes {
	return v.value
}

func (v *NullableTeamDataAttributes) Set(val *TeamDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamDataAttributes(val *TeamDataAttributes) *NullableTeamDataAttributes {
	return &NullableTeamDataAttributes{value: val, isSet: true}
}

func (v NullableTeamDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


