/*
User storage service

User storage service for recovery flow

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinksDirectLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinksDirectLinks{}

// LinksDirectLinks struct for LinksDirectLinks
type LinksDirectLinks struct {
	// Link to participants
	Self string `json:"self"`
	// Link to participants
	Related string `json:"related"`
}

type _LinksDirectLinks LinksDirectLinks

// NewLinksDirectLinks instantiates a new LinksDirectLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinksDirectLinks(self string, related string) *LinksDirectLinks {
	this := LinksDirectLinks{}
	this.Self = self
	this.Related = related
	return &this
}

// NewLinksDirectLinksWithDefaults instantiates a new LinksDirectLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinksDirectLinksWithDefaults() *LinksDirectLinks {
	this := LinksDirectLinks{}
	return &this
}

// GetSelf returns the Self field value
func (o *LinksDirectLinks) GetSelf() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Self
}

// GetSelfOk returns a tuple with the Self field value
// and a boolean to check if the value has been set.
func (o *LinksDirectLinks) GetSelfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Self, true
}

// SetSelf sets field value
func (o *LinksDirectLinks) SetSelf(v string) {
	o.Self = v
}

// GetRelated returns the Related field value
func (o *LinksDirectLinks) GetRelated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Related
}

// GetRelatedOk returns a tuple with the Related field value
// and a boolean to check if the value has been set.
func (o *LinksDirectLinks) GetRelatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Related, true
}

// SetRelated sets field value
func (o *LinksDirectLinks) SetRelated(v string) {
	o.Related = v
}

func (o LinksDirectLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinksDirectLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["self"] = o.Self
	toSerialize["related"] = o.Related
	return toSerialize, nil
}

func (o *LinksDirectLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"self",
		"related",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinksDirectLinks := _LinksDirectLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinksDirectLinks)

	if err != nil {
		return err
	}

	*o = LinksDirectLinks(varLinksDirectLinks)

	return err
}

type NullableLinksDirectLinks struct {
	value *LinksDirectLinks
	isSet bool
}

func (v NullableLinksDirectLinks) Get() *LinksDirectLinks {
	return v.value
}

func (v *NullableLinksDirectLinks) Set(val *LinksDirectLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableLinksDirectLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableLinksDirectLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinksDirectLinks(val *LinksDirectLinks) *NullableLinksDirectLinks {
	return &NullableLinksDirectLinks{value: val, isSet: true}
}

func (v NullableLinksDirectLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinksDirectLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


