/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TeamDataRelationshipsMembersDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamDataRelationshipsMembersDataInner{}

// TeamDataRelationshipsMembersDataInner struct for TeamDataRelationshipsMembersDataInner
type TeamDataRelationshipsMembersDataInner struct {
	// Member ID
	Id string `json:"id"`
	Type string `json:"type"`
}

type _TeamDataRelationshipsMembersDataInner TeamDataRelationshipsMembersDataInner

// NewTeamDataRelationshipsMembersDataInner instantiates a new TeamDataRelationshipsMembersDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamDataRelationshipsMembersDataInner(id string, type_ string) *TeamDataRelationshipsMembersDataInner {
	this := TeamDataRelationshipsMembersDataInner{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewTeamDataRelationshipsMembersDataInnerWithDefaults instantiates a new TeamDataRelationshipsMembersDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamDataRelationshipsMembersDataInnerWithDefaults() *TeamDataRelationshipsMembersDataInner {
	this := TeamDataRelationshipsMembersDataInner{}
	return &this
}

// GetId returns the Id field value
func (o *TeamDataRelationshipsMembersDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TeamDataRelationshipsMembersDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TeamDataRelationshipsMembersDataInner) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *TeamDataRelationshipsMembersDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TeamDataRelationshipsMembersDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TeamDataRelationshipsMembersDataInner) SetType(v string) {
	o.Type = v
}

func (o TeamDataRelationshipsMembersDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamDataRelationshipsMembersDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TeamDataRelationshipsMembersDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamDataRelationshipsMembersDataInner := _TeamDataRelationshipsMembersDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamDataRelationshipsMembersDataInner)

	if err != nil {
		return err
	}

	*o = TeamDataRelationshipsMembersDataInner(varTeamDataRelationshipsMembersDataInner)

	return err
}

type NullableTeamDataRelationshipsMembersDataInner struct {
	value *TeamDataRelationshipsMembersDataInner
	isSet bool
}

func (v NullableTeamDataRelationshipsMembersDataInner) Get() *TeamDataRelationshipsMembersDataInner {
	return v.value
}

func (v *NullableTeamDataRelationshipsMembersDataInner) Set(val *TeamDataRelationshipsMembersDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamDataRelationshipsMembersDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamDataRelationshipsMembersDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamDataRelationshipsMembersDataInner(val *TeamDataRelationshipsMembersDataInner) *NullableTeamDataRelationshipsMembersDataInner {
	return &NullableTeamDataRelationshipsMembersDataInner{value: val, isSet: true}
}

func (v NullableTeamDataRelationshipsMembersDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamDataRelationshipsMembersDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


