/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberCreateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberCreateDataAttributes{}

// MemberCreateDataAttributes struct for MemberCreateDataAttributes
type MemberCreateDataAttributes struct {
	// User ID
	UserId string `json:"user_id"`
	// Team ID
	TeamId string `json:"team_id"`
	// User role
	Role string `json:"role"`
	// Description
	Description *string `json:"description,omitempty"`
}

type _MemberCreateDataAttributes MemberCreateDataAttributes

// NewMemberCreateDataAttributes instantiates a new MemberCreateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberCreateDataAttributes(userId string, teamId string, role string) *MemberCreateDataAttributes {
	this := MemberCreateDataAttributes{}
	this.UserId = userId
	this.TeamId = teamId
	this.Role = role
	return &this
}

// NewMemberCreateDataAttributesWithDefaults instantiates a new MemberCreateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberCreateDataAttributesWithDefaults() *MemberCreateDataAttributes {
	this := MemberCreateDataAttributes{}
	return &this
}

// GetUserId returns the UserId field value
func (o *MemberCreateDataAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *MemberCreateDataAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *MemberCreateDataAttributes) SetUserId(v string) {
	o.UserId = v
}

// GetTeamId returns the TeamId field value
func (o *MemberCreateDataAttributes) GetTeamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *MemberCreateDataAttributes) GetTeamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *MemberCreateDataAttributes) SetTeamId(v string) {
	o.TeamId = v
}

// GetRole returns the Role field value
func (o *MemberCreateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MemberCreateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MemberCreateDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MemberCreateDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberCreateDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MemberCreateDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MemberCreateDataAttributes) SetDescription(v string) {
	o.Description = &v
}

func (o MemberCreateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberCreateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	toSerialize["team_id"] = o.TeamId
	toSerialize["role"] = o.Role
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *MemberCreateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
		"team_id",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberCreateDataAttributes := _MemberCreateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberCreateDataAttributes)

	if err != nil {
		return err
	}

	*o = MemberCreateDataAttributes(varMemberCreateDataAttributes)

	return err
}

type NullableMemberCreateDataAttributes struct {
	value *MemberCreateDataAttributes
	isSet bool
}

func (v NullableMemberCreateDataAttributes) Get() *MemberCreateDataAttributes {
	return v.value
}

func (v *NullableMemberCreateDataAttributes) Set(val *MemberCreateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberCreateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberCreateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberCreateDataAttributes(val *MemberCreateDataAttributes) *NullableMemberCreateDataAttributes {
	return &NullableMemberCreateDataAttributes{value: val, isSet: true}
}

func (v NullableMemberCreateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberCreateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


