/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberData{}

// MemberData struct for MemberData
type MemberData struct {
	// member id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes MemberDataAttributes `json:"attributes"`
	Relationships *MemberDataRelationships `json:"relationships,omitempty"`
}

type _MemberData MemberData

// NewMemberData instantiates a new MemberData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberData(id string, type_ string, attributes MemberDataAttributes) *MemberData {
	this := MemberData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewMemberDataWithDefaults instantiates a new MemberData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberDataWithDefaults() *MemberData {
	this := MemberData{}
	return &this
}

// GetId returns the Id field value
func (o *MemberData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemberData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemberData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *MemberData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MemberData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MemberData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *MemberData) GetAttributes() MemberDataAttributes {
	if o == nil {
		var ret MemberDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *MemberData) GetAttributesOk() (*MemberDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *MemberData) SetAttributes(v MemberDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *MemberData) GetRelationships() MemberDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret MemberDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberData) GetRelationshipsOk() (*MemberDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *MemberData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given MemberDataRelationships and assigns it to the Relationships field.
func (o *MemberData) SetRelationships(v MemberDataRelationships) {
	o.Relationships = &v
}

func (o MemberData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *MemberData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberData := _MemberData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberData)

	if err != nil {
		return err
	}

	*o = MemberData(varMemberData)

	return err
}

type NullableMemberData struct {
	value *MemberData
	isSet bool
}

func (v NullableMemberData) Get() *MemberData {
	return v.value
}

func (v *NullableMemberData) Set(val *MemberData) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberData) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberData(val *MemberData) *NullableMemberData {
	return &NullableMemberData{value: val, isSet: true}
}

func (v NullableMemberData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


