/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberUpdateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberUpdateDataAttributes{}

// MemberUpdateDataAttributes struct for MemberUpdateDataAttributes
type MemberUpdateDataAttributes struct {
	// User role
	Role string `json:"role"`
	// Description
	Description string `json:"description"`
}

type _MemberUpdateDataAttributes MemberUpdateDataAttributes

// NewMemberUpdateDataAttributes instantiates a new MemberUpdateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberUpdateDataAttributes(role string, description string) *MemberUpdateDataAttributes {
	this := MemberUpdateDataAttributes{}
	this.Role = role
	this.Description = description
	return &this
}

// NewMemberUpdateDataAttributesWithDefaults instantiates a new MemberUpdateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberUpdateDataAttributesWithDefaults() *MemberUpdateDataAttributes {
	this := MemberUpdateDataAttributes{}
	return &this
}

// GetRole returns the Role field value
func (o *MemberUpdateDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *MemberUpdateDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *MemberUpdateDataAttributes) SetRole(v string) {
	o.Role = v
}

// GetDescription returns the Description field value
func (o *MemberUpdateDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *MemberUpdateDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *MemberUpdateDataAttributes) SetDescription(v string) {
	o.Description = v
}

func (o MemberUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberUpdateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *MemberUpdateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberUpdateDataAttributes := _MemberUpdateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberUpdateDataAttributes)

	if err != nil {
		return err
	}

	*o = MemberUpdateDataAttributes(varMemberUpdateDataAttributes)

	return err
}

type NullableMemberUpdateDataAttributes struct {
	value *MemberUpdateDataAttributes
	isSet bool
}

func (v NullableMemberUpdateDataAttributes) Get() *MemberUpdateDataAttributes {
	return v.value
}

func (v *NullableMemberUpdateDataAttributes) Set(val *MemberUpdateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberUpdateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberUpdateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberUpdateDataAttributes(val *MemberUpdateDataAttributes) *NullableMemberUpdateDataAttributes {
	return &NullableMemberUpdateDataAttributes{value: val, isSet: true}
}

func (v NullableMemberUpdateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberUpdateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


