/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserCollectionDataAttributesUsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCollectionDataAttributesUsersInner{}

// UserCollectionDataAttributesUsersInner struct for UserCollectionDataAttributesUsersInner
type UserCollectionDataAttributesUsersInner struct {
	// Username
	Username string `json:"username"`
	// User role
	Role string `json:"role"`
	// User avatar
	Avatar string `json:"avatar"`
	// User created at
	CreatedAt time.Time `json:"created_at"`
}

type _UserCollectionDataAttributesUsersInner UserCollectionDataAttributesUsersInner

// NewUserCollectionDataAttributesUsersInner instantiates a new UserCollectionDataAttributesUsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCollectionDataAttributesUsersInner(username string, role string, avatar string, createdAt time.Time) *UserCollectionDataAttributesUsersInner {
	this := UserCollectionDataAttributesUsersInner{}
	this.Username = username
	this.Role = role
	this.Avatar = avatar
	this.CreatedAt = createdAt
	return &this
}

// NewUserCollectionDataAttributesUsersInnerWithDefaults instantiates a new UserCollectionDataAttributesUsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCollectionDataAttributesUsersInnerWithDefaults() *UserCollectionDataAttributesUsersInner {
	this := UserCollectionDataAttributesUsersInner{}
	return &this
}

// GetUsername returns the Username field value
func (o *UserCollectionDataAttributesUsersInner) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserCollectionDataAttributesUsersInner) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserCollectionDataAttributesUsersInner) SetUsername(v string) {
	o.Username = v
}

// GetRole returns the Role field value
func (o *UserCollectionDataAttributesUsersInner) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UserCollectionDataAttributesUsersInner) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UserCollectionDataAttributesUsersInner) SetRole(v string) {
	o.Role = v
}

// GetAvatar returns the Avatar field value
func (o *UserCollectionDataAttributesUsersInner) GetAvatar() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value
// and a boolean to check if the value has been set.
func (o *UserCollectionDataAttributesUsersInner) GetAvatarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Avatar, true
}

// SetAvatar sets field value
func (o *UserCollectionDataAttributesUsersInner) SetAvatar(v string) {
	o.Avatar = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserCollectionDataAttributesUsersInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserCollectionDataAttributesUsersInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserCollectionDataAttributesUsersInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o UserCollectionDataAttributesUsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCollectionDataAttributesUsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["role"] = o.Role
	toSerialize["avatar"] = o.Avatar
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *UserCollectionDataAttributesUsersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"role",
		"avatar",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserCollectionDataAttributesUsersInner := _UserCollectionDataAttributesUsersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserCollectionDataAttributesUsersInner)

	if err != nil {
		return err
	}

	*o = UserCollectionDataAttributesUsersInner(varUserCollectionDataAttributesUsersInner)

	return err
}

type NullableUserCollectionDataAttributesUsersInner struct {
	value *UserCollectionDataAttributesUsersInner
	isSet bool
}

func (v NullableUserCollectionDataAttributesUsersInner) Get() *UserCollectionDataAttributesUsersInner {
	return v.value
}

func (v *NullableUserCollectionDataAttributesUsersInner) Set(val *UserCollectionDataAttributesUsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCollectionDataAttributesUsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCollectionDataAttributesUsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCollectionDataAttributesUsersInner(val *UserCollectionDataAttributesUsersInner) *NullableUserCollectionDataAttributesUsersInner {
	return &NullableUserCollectionDataAttributesUsersInner{value: val, isSet: true}
}

func (v NullableUserCollectionDataAttributesUsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCollectionDataAttributesUsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


