openapi: 3.0.0
info:
  description: SSO REST API for Cifra app
  title: Cifra SSO REST API
  version: 0.0.1
servers:
- url: /
paths:
  /users/create:
    post:
      operationId: createUser
      responses:
        "201":
          description: Created
      summary: Create a new user
components:
  schemas:
    User:
      properties:
        data:
          $ref: '#/components/schemas/User_data'
      required:
      - data
      type: object
    UserUpdate:
      properties:
        data:
          $ref: '#/components/schemas/UserUpdate_data'
      required:
      - data
      type: object
    UserCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/User'
          type: array
        links:
          $ref: '#/components/schemas/Links'
      required:
      - data
      - links
      type: object
    Links:
      properties:
        previous:
          description: Link to the previous page
          type: string
        self:
          description: Link to the current page
          type: string
        next:
          description: Link to the next page
          type: string
      type: object
    User_data_attributes_ban:
      properties:
        status:
          description: Ban status
          type: boolean
        start:
          description: Ban start date
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        end:
          description: Ban end date
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        sort:
          description: Type of block
          type: string
        desc:
          description: Reason for ban and explanation
          type: string
        initiator:
          description: Ban initiator id
          type: string
      required:
      - desc
      - end
      - initiator
      - sort
      - start
      - status
      type: object
    User_data_attributes:
      properties:
        username:
          description: Username
          type: string
        role:
          description: User role
          type: string
        avatar:
          description: User avatar
          type: string
        updated_at:
          description: User updated
          format: date-time
          type: string
        created_at:
          description: User created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        organizations:
          description: User organization
          items:
            type: string
          type: array
        projects:
          description: User projects
          items:
            type: string
          type: array
        ideas:
          description: User ideas
          items:
            type: string
          type: array
        reports_sent:
          description: User reports sent
          items:
            type: string
          type: array
        reports_received:
          description: User reports received
          items:
            type: string
          type: array
        ban:
          $ref: '#/components/schemas/User_data_attributes_ban'
      required:
      - avatar
      - created_at
      - role
      - username
      type: object
    User_data:
      properties:
        id:
          description: User ID
          type: string
        type:
          enum:
          - user
          type: string
        attributes:
          $ref: '#/components/schemas/User_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UserUpdate_data_attributes:
      properties:
        username:
          description: Username
          type: string
        description:
          description: User description
          type: string
        role:
          description: User role
          type: string
      type: object
    UserUpdate_data:
      properties:
        id:
          description: User ID
          type: string
        type:
          enum:
          - user_update
          type: string
        attributes:
          $ref: '#/components/schemas/UserUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
