openapi: 3.0.0
info:
  description: SSO REST API for Cifra app
  title: Cifra SSO REST API
  version: 0.0.1
servers:
- url: /
paths:
  /users/create:
    post:
      operationId: createUser
      responses:
        "201":
          description: Created
      summary: Create a new user
components:
  schemas:
    User:
      properties:
        data:
          $ref: '#/components/schemas/User_data'
      required:
      - data
      type: object
    UserUpdate:
      properties:
        data:
          $ref: '#/components/schemas/UserUpdate_data'
      required:
      - data
      type: object
    UserCollection:
      properties:
        data:
          $ref: '#/components/schemas/UserCollection_data'
      required:
      - data
      type: object
    User_data_attributes:
      properties:
        username:
          description: Username
          type: string
        description:
          description: User description
          type: string
        role:
          description: User role
          type: string
        avatar:
          description: User avatar
          type: string
        created_at:
          description: User created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - avatar
      - created_at
      - role
      - username
      type: object
    User_data:
      properties:
        id:
          description: User ID
          type: string
        type:
          enum:
          - user
          type: string
        attributes:
          $ref: '#/components/schemas/User_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UserUpdate_data_attributes:
      properties:
        username:
          description: Username
          type: string
        description:
          description: User description
          type: string
        role:
          description: User role
          type: string
      type: object
    UserUpdate_data:
      properties:
        id:
          description: User ID
          type: string
        type:
          enum:
          - user_update
          type: string
        attributes:
          $ref: '#/components/schemas/UserUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UserCollection_data_attributes_users_inner:
      properties:
        username:
          description: Username
          type: string
        role:
          description: User role
          type: string
        avatar:
          description: User avatar
          type: string
        created_at:
          description: User created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - avatar
      - created_at
      - role
      - username
      type: object
    UserCollection_data_attributes:
      properties:
        users:
          items:
            $ref: '#/components/schemas/UserCollection_data_attributes_users_inner'
          type: array
      required:
      - users
      type: object
    UserCollection_data:
      properties:
        type:
          enum:
          - user_collection
          type: string
        attributes:
          $ref: '#/components/schemas/UserCollection_data_attributes'
      required:
      - attributes
      - type
      type: object
