openapi: 3.0.0
info:
  title: User storage service
  description: User storage service for recovery flow
  version: 0.0.1
paths:
  /test:
    post:
      summary: Test
      operationId: test
      responses:
        '201':
          description: Ok
components:
  schemas:
    User:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/UserData'
    UserData:
      type: object
      required:
        - id
        - type
        - attributes
        - links
      properties:
        id:
          type: string
          format: uuid
          description: User ID
        type:
          type: string
          enum:
            - user
        attributes:
          $ref: '#/components/schemas/UserAttributes'
        links:
          $ref: '#/components/schemas/LinksSelf'
    UserAttributes:
      type: object
      required:
        - username
        - verified
        - created_at
      properties:
        username:
          type: string
          description: Username
        type:
          type: string
          description: Type
        avatar:
          type: string
          description: Avatar
        title_name:
          type: string
          description: Title
        verified:
          type: boolean
          description: Verified
        speciality:
          type: string
          description: Speciality
        position:
          type: string
          description: Position
        city:
          type: string
          description: City
        country:
          type: string
          description: Country
        date_of_birth:
          type: string
          format: date-time
          description: Date of birthday (YYYY-MM-DD)
        updated_at:
          type: string
          format: date-time
          description: Updated at
        created_at:
          type: string
          format: date-time
          description: Created at
    UserUpdate:
      type: object
      required:
        - data
      properties:
        data:
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - user_update
            attributes:
              type: object
              properties:
                username:
                  type: string
                  description: Username
                verified:
                  type: boolean
                  description: User verified status
                title_name:
                  type: string
                  description: User title name
                speciality:
                  type: string
                  description: User speciality
                position:
                  type: string
                  description: User position
                city:
                  type: string
                  description: User city
                country:
                  type: string
                  description: User country
                date_of_birth:
                  type: string
                  format: date
                  description: User date of birth
    UsersCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserData'
        links:
          $ref: '#/components/schemas/LinksPagination'
    LinksSelf:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          description: Link to resources
        update:
          type: string
          description: Link to update resources
    LinksDirect:
      type: object
      required:
        - links
      properties:
        links:
          type: object
          required:
            - self
            - related
            - data
          properties:
            self:
              type: string
              description: Link to participants
            related:
              type: string
              description: Link to participants
        data:
          type: object
          required:
            - id
            - type
          properties:
            id:
              type: string
              description: resources id
            type:
              type: string
              description: resources type
    LinksPagination:
      type: object
      required:
        - self
      properties:
        previous:
          type: string
          description: Link to the previous page
        self:
          type: string
          description: Link to the current page
        next:
          type: string
          description: Link to the next page
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
