openapi: 3.0.0
info:
  title: User storage service
  description: User storage service for recovery flow
  version: 0.0.1

paths:
  /private/users/:
    $ref: './paths/UserUpdate.yaml'
  /private/users/avatar:
    $ref: './paths/UserAvatar.yaml'
  /public/users/search:
    $ref: './paths/UserSearch.yaml'
  /public/users/filter:
    $ref: './paths/UserFilter.yaml'
  /public/users/{user_id}:
    $ref: './paths/UserGetById.yaml'
  /admin/users/{user_id}:
    $ref: './paths/AdminUserUpdate.yaml'
  /admin/users/{user_id}/avatar:
    $ref: './paths/AdminUserAvatar.yaml'

components:
  schemas:
    User:
      $ref: './spec/components/schemas/User.yaml'
    UserUpdate:
      $ref: './spec/components/schemas/UserUpdate.yaml'
    UserCollection:
      $ref: './spec/components/schemas/UserCollection.yaml'
    Links:
      $ref: './spec/components/schemas/Links.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT