openapi: 3.0.0
info:
  title: User storage service
  description: User storage service for recovery flow
  version: 0.0.1

paths:
  /test:
    post:
      summary: Test
      operationId: test
      responses:
        '201':
          description: "Ok"

components:
  schemas:
    User:
      $ref: './spec/components/schemas/User.yaml'
    UserData:
      $ref: './spec/components/schemas/UserData.yaml'
    UserAttributes:
      $ref: './spec/components/schemas/UserAttributes.yaml'
    UserUpdate:
      $ref: './spec/components/schemas/UserUpdate.yaml'
    UsersCollection:
      $ref: './spec/components/schemas/UsersCollection.yaml'
    LinksSelf:
      $ref: './spec/components/schemas/LinksSelf.yaml'
    LinksDirect:
      $ref: './spec/components/schemas/LinksDirect.yaml'
    LinksPagination:
      $ref: './spec/components/schemas/LinksPagination.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT